version: "3.8"

services:
  web:
    build: .
    environment:
      - DT_ENVIRONMENTID=rha75589
      - DT_APPLICATIONID=PythonSnekApp
      - DT_ENABLEMULTIPROCESSINGINSTRUMENTATION=true
      - DT_PYTHONPATH=/usr/local/bin/python3
      - DT_LOGGING_LEVEL=INFO
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1G
    command: >
      sh -c "uvicorn app.main:app
      --host 0.0.0.0
      --port 8080
      --proxy-headers"
